function renderOrders(d,s,filter,q='',city='',esc,money,normPhone,csrf){
  const visible=d.orders.filter(o=>!o.archivedAt);
  const unread=visible.filter(o=>o.readAt===null).length;
  const query=String(q||'').trim().toLowerCase();
  const orders=visible.slice().reverse().filter(o=>
    (filter==='all'||(filter==='new'&&o.readAt===null)||(filter==='active'&&!['مكتمل','ملغي'].includes(o.status))||(filter==='done'&&o.status==='مكتمل')||(filter==='cancel'&&o.status==='ملغي'))&&
    (!query||[o.id,o.name,o.phone,o.city,o.area].join(' ').toLowerCase().includes(query))&&
    (!city||o.city===city)
  );
  const cards=orders.map(o=>{
    const items=(o.items||[]).map(i=>'<div class="row"><span>'+esc(i.name)+' × '+i.q+'</span><b>'+money((+i.price||0)*(+i.q||0))+' '+esc(s.currency)+'</b></div>').join('');
    const status=['جديد','مؤكد','قيد التجهيز','قيد التوصيل','مكتمل','ملغي'].map(z=>'<option '+(z===o.status?'selected':'')+'>'+z+'</option>').join('');
    const unreadBadge=o.readAt===null?'<span class="pill new">طلب جديد</span>':'<span class="pill">مقروء</span>';
    const readBtn=o.readAt===null?'<form method="post" action="/admin/read"><input type="hidden" name="csrf" value="'+csrf+'"><input type="hidden" name="id" value="'+o.id+'"><button class="btn">تعليم كمقروء</button></form>':'';
    const note=o.notes?'<div class="muted" style="margin-top:10px">ملاحظة: '+esc(o.notes)+'</div>':'';
    return '<article class="orderCard '+(o.readAt===null?'unread':'')+'"><div class="orderTop"><div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><b style="font-size:18px">'+esc(o.name)+'</b>'+unreadBadge+'<span class="pill">'+esc(o.status)+'</span></div><div class="orderMeta"><span>#'+esc(o.id)+'</span><span>•</span><span>'+new Date(o.created).toLocaleString('ar-LY')+'</span></div></div><b style="font-size:20px">'+money(o.total)+' '+esc(s.currency)+'</b></div><div class="orderGrid"><div><small>الهاتف</small><b>'+esc(o.phone)+'</b></div><div><small>المدينة</small><b>'+esc(o.city)+'</b></div><div><small>المنطقة</small><b>'+esc(o.area||'—')+'</b></div><div><small>العنوان</small><b>'+esc(o.address)+'</b></div></div><div style="margin-top:12px"><small class="muted">المنتجات</small>'+items+note+'</div><div class="orderActions"><form method="post" action="/admin/status"><input type="hidden" name="csrf" value="'+csrf+'"><input type="hidden" name="id" value="'+o.id+'"><select class="input" name="status" onchange="this.form.submit()">'+status+'</select></form>'+readBtn+'<a class="btn hot" target="_blank" rel="noopener" href="https://wa.me/'+normPhone(o.phone)+'?text='+encodeURIComponent('مرحبًا '+o.name+'، بخصوص طلبك رقم '+o.id)+'">واتساب</a><form method="post" action="/admin/order-archive" onsubmit="return confirm(\'هل تريد إخفاء هذا الطلب من القائمة؟\')"><input type="hidden" name="csrf" value="'+csrf+'"><input type="hidden" name="id" value="'+o.id+'"><button class="btn danger">حذف من القائمة</button></form></div></article>';
  }).join('');
  const cities=[...new Set(visible.map(o=>o.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'));
  const cityOptions=cities.map(c=>'<option value="'+esc(c)+'" '+(c===city?'selected':'')+'>'+esc(c)+'</option>').join('');
  const exportUrl='/admin/orders.csv?of='+encodeURIComponent(filter)+'&oq='+encodeURIComponent(q||'')+'&city='+encodeURIComponent(city||'');
  return '<section id="orders" class="adminbox" style="margin-top:16px"><div class="ordersHead"><div><h3 style="margin:0">الطلبات</h3><div class="muted">'+unread+' طلب جديد · '+visible.length+' طلب ظاهر · '+orders.length+' نتيجة</div></div><div class="orderFilters"><a class="btn" href="/admin?of=all#orders">الكل</a><a class="btn" href="/admin?of=new#orders">الجديدة</a><a class="btn" href="/admin?of=active#orders">النشطة</a><a class="btn" href="/admin?of=done#orders">المكتملة</a><a class="btn" href="/admin?of=cancel#orders">الملغية</a></div></div><form class="filterPanel" method="get" action="/admin#orders" style="margin:12px 0"><input type="hidden" name="of" value="'+esc(filter)+'"><div class="two"><div class="field"><label>بحث في الطلبات</label><input class="input" name="oq" value="'+esc(q||'')+'" placeholder="الاسم، الهاتف، رقم الطلب..." autocomplete="off"></div><div class="field"><label>المدينة</label><select class="input" name="city"><option value="">كل المدن</option>'+cityOptions+'</select></div></div><div class="filterActions"><button class="btn hot">بحث وتصفية</button><a class="btn" href="/admin#orders">مسح</a><a class="btn" href="'+exportUrl+'">تصدير CSV</a></div></form><div class="notifyBar"><span>🔔</span><span class="muted">فعّل إشعارات المتصفح وسيتم فحص الطلبات الجديدة تلقائيًا أثناء فتح لوحة الإدارة.</span><button class="btn" type="button" onclick="enableOrderNotifications()">تفعيل التنبيه</button></div>'+(cards||'<div class="ordersEmpty">لا توجد طلبات مطابقة للبحث الحالي.</div>')+'</section>';
}

const css='.ordersHead{display:flex;gap:10px;flex-wrap:wrap;align-items:center;justify-content:space-between;margin-bottom:14px}.orderFilters{display:flex;gap:8px;flex-wrap:wrap}.pill{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:99px;border:1px solid #303640;font-size:12px;font-weight:900}.pill.new{background:#d8ff45;color:#111;border-color:#d8ff45}.orderCard{border:1px solid #2b323c;border-radius:18px;padding:16px;margin:12px 0;background:#0f1318}.orderCard.unread{border-color:#d8ff45;box-shadow:0 0 0 1px rgba(216,255,69,.22)}.orderTop{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.orderMeta{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.orderGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px}.orderGrid div{background:#12171d;border:1px solid #252c34;border-radius:12px;padding:10px}.orderGrid small{display:block;color:#8e95a2;margin-bottom:4px}.orderActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.badgeCount{background:#ff5f6d;color:#fff;border-radius:99px;padding:2px 7px;font-size:11px;font-weight:900}.ordersEmpty{text-align:center;padding:28px;color:#8e95a2}.notifyBar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0 16px}@media(max-width:900px){.orderGrid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.orderGrid{grid-template-columns:1fr}.orderTop{flex-direction:column}}';
module.exports={renderOrders,css};
