const fs=require('fs'),path=require('path'),crypto=require('crypto');
const CUSTOMER=require('./customer-account'),LOCATIONS=require('./libya-locations');
const FILE=path.join(process.env.DATA_DIR||path.join(__dirname,'data'),'store.json');
const SECRET=process.env.CUSTOMER_SESSION_SECRET||crypto.createHash('sha256').update('nova-mobile:'+String(process.env.NEON_DATABASE_URL||'local-dev')).digest('hex');
const S=()=>{try{return JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{return {settings:{},products:[],orders:[],customers:[]}}};
const W=d=>fs.writeFileSync(FILE,JSON.stringify(d,null,2));
const phone=v=>String(v||'').replace(/\D/g,'');
const validPhone=v=>/^09\d{8}$/.test(phone(v));
const safe=c=>{if(!c)return null;const {passwordHash,passwordSalt,...rest}=c;return rest};
const cleanProduct=p=>({id:p.id,name:p.name,cat:p.cat||'',price:+p.price||0,old:+p.old||0,stock:Math.max(0,+p.stock||0),img:p.img||'',images:Array.isArray(p.images)?p.images.filter(Boolean).slice(0,7):[],desc:p.desc||''});
const cleanOrder=o=>({id:o.id,created:o.created,status:o.status,name:o.name,phone:o.phone,city:o.city,area:o.area,address:o.address,notes:o.notes||'',items:Array.isArray(o.items)?o.items:[],total:+o.total||0});
function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization','access-control-allow-methods':'GET, POST, PATCH, OPTIONS','x-content-type-options':'nosniff'});res.end(JSON.stringify(body))}
function version(c){return crypto.createHash('sha256').update(String(c.passwordHash||'')).digest('hex').slice(0,20)}
function token(c){const p=Buffer.from(JSON.stringify({sub:c.id,exp:Math.floor(Date.now()/1000)+2592000,pv:version(c)})).toString('base64url');const s=crypto.createHmac('sha256',SECRET).update('nova-mobile:'+p).digest('base64url');return p+'.'+s}
function current(req,d){const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return null;const [p,s]=h.slice(7).trim().split('.');if(!p||!s)return null;const x=crypto.createHmac('sha256',SECRET).update('nova-mobile:'+p).digest('base64url');const a=Buffer.from(s),b=Buffer.from(x);if(!a.length||a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;let j;try{j=JSON.parse(Buffer.from(p,'base64url').toString('utf8'))}catch{return null}if(!j.sub||j.exp<Math.floor(Date.now()/1000))return null;const c=(d.customers||[]).find(v=>v.id===j.sub);return c&&j.pv===version(c)?c:null}
function read(req){return new Promise((ok,no)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1e6)no(Error('large'))});req.on('end',()=>{try{const x=JSON.parse(d||'{}');ok(x&&typeof x==='object'&&!Array.isArray(x)?x:null)}catch{ok(null)}})})}
async function notifyTelegram(order,settings){
 const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.TELEGRAM_CHAT_ID;if(!token||!chatId)return false;
 const lines=['📱 طلب جديد من تطبيق NOVA STORE','', 'رقم الطلب: '+order.id,'العميل: '+order.name,'الهاتف: '+order.phone,'المدينة: '+order.city,'المنطقة: '+(order.area||'-'),'العنوان: '+order.address,'',...(order.items||[]).map(i=>'• '+i.name+' × '+i.q),'','الإجمالي: '+order.total+' '+(settings?.currency||'د.ل')];
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),6000);
 try{const r=await fetch('https://api.telegram.org/bot'+token+'/sendMessage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,text:lines.join('\n')}),signal:controller.signal});if(!r.ok){console.error('Mobile Telegram notify failed with status',r.status);return false}return true}catch(e){console.error('Mobile Telegram notify failed:',e.message);return false}finally{clearTimeout(timer)}
}
async function handle(req,res){
 const u=new URL(req.url,'http://nova.local'),p=u.pathname;if(!p.startsWith('/api/mobile/'))return false;
 if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'content-type, authorization','access-control-allow-methods':'GET, POST, PATCH, OPTIONS'});res.end();return true}
 if(req.method==='GET'&&p==='/api/mobile/bootstrap'){const d=S();json(res,200,{ok:true,settings:{name:d.settings.name,en:d.settings.en,tag:d.settings.tag,currency:d.settings.currency,ship:+d.settings.ship||0,free:+d.settings.free||0,wa:d.settings.wa||''},products:(d.products||[]).map(cleanProduct),locations:LOCATIONS});return true}
 if(req.method==='POST'&&p==='/api/mobile/register'){const x=await read(req);if(!x){json(res,400,{error:'بيانات التسجيل غير صالحة'});return true}const d=S(),r=CUSTOMER.register(d,x);if(r.error){json(res,400,{error:r.error});return true}W(d);json(res,201,{token:token(r.customer),customer:safe(r.customer)});return true}
 if(req.method==='POST'&&p==='/api/mobile/login'){const x=await read(req);if(!x){json(res,400,{error:'بيانات الدخول غير صالحة'});return true}const d=S(),r=CUSTOMER.login(d,x.phone,x.password);if(r.error){json(res,401,{error:r.error});return true}json(res,200,{token:token(r.customer),customer:safe(r.customer)});return true}
 if(req.method==='GET'&&p==='/api/mobile/me'){const d=S(),c=current(req,d);if(!c){json(res,401,{error:'يجب تسجيل الدخول'});return true}json(res,200,{customer:safe(c)});return true}
 if(req.method==='PATCH'&&p==='/api/mobile/profile'){const x=await read(req),d=S(),c=current(req,d);if(!c){json(res,401,{error:'يجب تسجيل الدخول'});return true}if(!x){json(res,400,{error:'البيانات غير صالحة'});return true}const r=CUSTOMER.updateProfile(d,c,{name:x.name??c.name,phone:x.phone??c.phone,phone2:x.phone2??c.phone2,email:x.email??c.email,city:x.city??c.city,area:x.area??c.area,address:x.address??c.address,landmark:x.landmark??c.landmark});if(r.error){json(res,400,{error:r.error});return true}W(d);json(res,200,{customer:safe(c)});return true}
 if(req.method==='GET'&&p==='/api/mobile/orders'){const d=S(),c=current(req,d);if(!c){json(res,401,{error:'يجب تسجيل الدخول'});return true}json(res,200,{orders:(d.orders||[]).filter(o=>o.customerId===c.id&&!o.archivedAt).slice().reverse().slice(0,50).map(cleanOrder)});return true}
 if(req.method==='GET'&&p==='/api/mobile/track'){const d=S(),c=current(req,d),id=String(u.searchParams.get('id')||'').trim(),ph=phone(u.searchParams.get('phone')),o=(d.orders||[]).find(v=>v.id===id&&!v.archivedAt);if(!o||!((c&&o.customerId===c.id)||(ph&&phone(o.phone)===ph))){json(res,404,{error:'لم يتم العثور على الطلب'});return true}json(res,200,{order:cleanOrder(o)});return true}
 if(req.method==='POST'&&p==='/api/mobile/order'){const x=await read(req),d=S(),c=current(req,d);if(!x){json(res,400,{error:'بيانات الطلب غير صالحة'});return true}const name=String(x.name||c?.name||'').trim(),ph=phone(x.phone||c?.phone||''),city=String(x.city||c?.city||'').trim(),area=String(x.area||c?.area||'').trim(),address=String(x.address||c?.address||'').trim(),notes=String(x.notes||'').trim().slice(0,1000);if(!name||!ph||!city||!area||!address||!Array.isArray(x.items)||!x.items.length){json(res,400,{error:'أكمل الاسم والهاتف والمدينة والمنطقة والعنوان والسلة'});return true}if(!validPhone(ph)){json(res,400,{error:'رقم الهاتف يجب أن يكون 10 أرقام ويبدأ بـ 09'});return true}if(!LOCATIONS[city]||!LOCATIONS[city].includes(area)){json(res,400,{error:'اختر المدينة والمنطقة من القوائم المتاحة'});return true}const items=[];for(const i of x.items){const z=(d.products||[]).find(v=>v.id===i.id);if(!z||+z.stock<=0)continue;const q=Math.min(Math.max(1,Math.min(Math.floor(+i.q||1),20)),Math.floor(+z.stock||0));if(q>0)items.push({id:z.id,name:z.name,price:+z.price||0,q})}if(!items.length){json(res,400,{error:'لا توجد منتجات متاحة في السلة'});return true}const sub=items.reduce((a,i)=>a+i.price*i.q,0),ship=sub>=(+d.settings.free||0)?0:(+d.settings.ship||0),id='ORD-'+Date.now().toString(36).toUpperCase();for(const i of items){const z=d.products.find(v=>v.id===i.id);z.stock=Math.max(0,(+z.stock||0)-i.q)}const o={id,created:new Date().toISOString(),status:'جديد',readAt:null,archivedAt:null,customerId:c?.id||null,name,phone:ph,city,area,address,notes,items,total:sub+ship,inventoryRestored:false};d.orders.push(o);W(d);await notifyTelegram(o,d.settings);json(res,201,{order:cleanOrder(o)});return true}
 json(res,404,{error:'API endpoint not found'});return true
}
module.exports={handle};
